### ISSUE TITLE
[BUG]  Login not working

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/anon-chat-app#10]
### Description

Login isn't working because of the `sawo` library which is used for passwordless authentication is having some server issues

change the login method, using another library for passwordless or implementing it yourself

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/176915762-6f71e4de-3e43-4c66-a710-6c33c9454ea4.png)

_No response_

**Comment by code-with-onye** [comment]
Hello Dunsin, i think the issue should be from the api, verify if it correspond correctly. 
https://docs.sawolabs.com/sawo/faqs

**Comment by Dun-sin** [comment]
> Hello Dunsin, i think the issue should be from the api, verify if it correspond correctly. https://docs.sawolabs.com/sawo/faqs

The service is actually non-functional at the moment, you can't even login to their website if you try

**Comment by code-with-onye** [comment]
Oh, you're right. How about utilizing Firebase instead?

**Comment by Dun-sin** [comment]
> Oh, you're right. How about utilizing Firebase instead?

So I thought of that but I saw no use of using a huge database service just to authenticate users when I won't even store the information in firebase.

The baseline point of firebase is to store something, authentication is just a side feature.

**Comment by code-with-onye** [comment]
Not actually, Firebase is a tool set that provides you with everything you need to easily build a backend application. You can choose to use just the authentication option and ignore the rest providers, just like a toolbox where you have all kinds of tools to get a job done, but you have to choose the right tool in the tool box to get a specific job done.

**Comment by Dun-sin** [comment]
> Not actually, Firebase is a tool set that provides you with everything you need to easily build a backend application. You can choose to use just the authentication option and ignore the rest providers, just like a toolbox where you have all kinds of tools to get a job done, but you have to choose the right tool in the tool box to get a specific job done.

yep i also know that, but i honestly don't want to use a whole big service, just so i can check if a user uses a valid email, to me it makes no sense.
I would use Auth0 instead

**Comment by code-with-onye** [comment]
good taste, comrade

**Comment by code-with-onye** [comment]
I've used Auth0 for login authentication, but I don't believe Auth0 supports anonymous login.

**Comment by Dun-sin** [comment]
> I've used Auth0 for login authentication, but I don't believe Auth0 supports anonymous login.

no, anonymous login isn't the point here, passwordless login is what im trying to use, which is why sawolabs was my best option because it does just that and nothing more really

**Comment by code-with-onye** [comment]
Ooh, passwordless, it does support that, but it is no longer an anonymous chat application. you know that, right?

**Comment by Dun-sin** [comment]
> Ooh, passwordless, it does support that, but it is no longer an anonymous chat application. you know that, right?

it is, read the conversation in this issue #14

**Comment by code-with-onye** [comment]
Ooh I see
