### ISSUE TITLE
[FEATURE] Gitpodify Project

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/anon-chat-app#11]
### Description

- Add the gitpod button in the `README`
- Add `gitpod.yml` file

**Comment by Dharmik48** [comment]
Let me try to solve this issue. I am not a Gitpod master, but I'll make it work.

**Comment by Dun-sin** [comment]
> Let me try to solve this issue. I am not a Gitpod master, but I'll make it work.

alright go for it
