### ISSUE TITLE
[BUG] Make the `Login Anonymously` button work

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/anon-chat-app#14]
### Description

The button has no functionality yet, make the button authenitcate the user but not store anything in the mongodb database

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/176849749-f71c5647-7c7b-4cc8-88d5-127374165add.png)

**Comment by Dharmik48** [comment]
Why do need a Login button in an app to chat _anonymously_?

**Comment by Dun-sin** [comment]
> Why do need a Login button in an app to chat _anonymously_?

so the user can use the website anywhere else.

**Comment by Dharmik48** [comment]
> not store anything in the mongodb database

If we don't store anything about the user in the DB then how will we even authenticate the user, as there is no data to verify the credentials?

**Comment by Dun-sin** [comment]
> If we don't store anything about the user in the DB then how will we even authenticate the user, as there is no data to verify the credentials?

There are two issues #14 #10

#14 for anonymous button: for users who don't want anything about them stored-(this current issue you are chatting at) 

#10 for users who want to be able to keep their previous chats in mongodb

**Comment by Dharmik48** [comment]
Oh! Got it 👍🏻 Didn't know about #10😅

**Comment by mathiasayivor** [comment]
@Dun-sin I'd like to work on this.... may I proceed?

**Comment by Dun-sin** [comment]
> @Dun-sin I'd like to work on this.... may I proceed?

Go ahead
