### ISSUE TITLE
[BUG] Misplacement of semicolon in the sign-in page

### ISSUE THREAD

**Issue by Sreekar-Shodhan** [Dun-sin/anon-chat-app#23]
### Description

When I opened the website from readme, First the sign in page has appeared. After scrolling down, there is a white space and semi-colon at the bottom left of the page.

I would like to work on this issue. Can you please assign this issue to me.

### Screenshots

![image](https://user-images.githubusercontent.com/71596539/178155481-2d79e85f-2b67-475f-a4a1-137f4042ee98.png)

**Comment by Dun-sin** [comment]
Oh yeah I saw that, but was too lazy to fix to lol. Thanks for volunteering. Go ahead

**Comment by Sreekar-Shodhan** [comment]
Hey Iam not that familira with react, backend code. Can I please know how to open your code in browser to see the output. Like normally in VS code I click the open in browser but its not showing in any file. 

And also is there any index.html? I cant find where did that extra semi colon came from.

**Comment by Dun-sin** [comment]
This has been fixed with the lastest changes, thanks for letting me know
