### ISSUE TITLE
[DOCS] <Spelling mistake>

### ISSUE THREAD

**Issue by Sreekar-Shodhan** [Dun-sin/anon-chat-app#24]
### Description

I think there is a spelling mistake in the bottom of README. Its cheers and not beers ig.
And also full-stop at the end of the sentence. 

### Screenshots

![image](https://user-images.githubusercontent.com/71596539/178155667-825898c3-5905-4a29-b85b-614af764fd27.png)

**Comment by Dun-sin** [comment]
No need to do this hehe
