### ISSUE TITLE
[DOCS] Better instructions for making changes in the code.

### ISSUE THREAD

**Issue by Darshan174** [Dun-sin/anon-chat-app#27]
### Description

As a beginner, it was quit easy and understandable for me to follow till step 6. Later from step 7, I'd no clue to make changes in the source code and on how to stage those changes. I'm sharing my perspective so that even beginners with potential can contribute and grow this project. I'm really interested in this project, looking forward for further better instructions.

**Comment by Dun-sin** [comment]
Fixed in #28, hope it makes it better
