### ISSUE TITLE
[BUG] Blank Page on first ever load

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/anon-chat-app#35]
### Description

On first ever load the app is only showing a blank page.
You'd have to refresh again to get the actual app. I think it's a problem with initialization?

To get what I'm talking about, visit [The App Url](https://anon-chat-app.vercel.app), open console and clear all local data  i.e `localStorage.clear()`, then refresh the page.

**Comment by devXprite** [comment]
Same with me!

![anon chat](https://user-images.githubusercontent.com/80192140/179341568-c4b6f885-47f2-4b5f-9686-2348f177ce90.PNG)

**Comment by Dun-sin** [comment]
well the app isn't half ready yet, like even if that works you can't chat
