### ISSUE TITLE
[DOCS] Add documentation for configuring dev environment for /server and /client directories

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/anon-chat-app#38]
### Description

Currently, there's no documentation on how to configure your dev environment for /server directory, which would make it difficult for future contributions.

**Comment by Dun-sin** [comment]
npm install.......

**Comment by mathiasayivor** [comment]
> npm install.......

![Screenshot from 2022-07-17 11-32-09](https://user-images.githubusercontent.com/74247733/179396137-7a858289-bd5d-4aaa-a6ee-cde46f800a7f.png)

**Comment by mathiasayivor** [comment]
I had to create the .env file myself, install mongodb & configure it to work with the existing code.

**Comment by Dun-sin** [comment]
did you read `contributing.md`?

**Comment by mathiasayivor** [comment]
> I had to create the .env file myself, install mongodb & configure it to work with the existing code.

.env files are not commited by git, they're being ignored

**Comment by mathiasayivor** [comment]
> did you read `contributing.md`?

Yep.
but nothing is included regarding db, configs, etc... only git/github related instructions are there

**Comment by Dun-sin** [comment]
> .env files are not commited by git, they're being ignored

yep, that I know, no worries I'm adding it soon to GitHub

**Comment by mathiasayivor** [comment]
I'm currently working trying to make MojoAuth work... currently, apiKey is undefined cos it's being read from `process.env.REACT_APP_IMPORTANT` which i don't have access to: 
```
    const apiKey = process.env.REACT_APP_IMPORTANT;
    const mojoauth = new MojoAuth(apiKey, {
        source: [{ type: 'email', feature: 'magiclink' }]
    });
```

**Comment by mathiasayivor** [comment]
> > .env files are not commited by git, they're being ignored
> 
> yep, that I know, no worries I'm adding it soon to GitHub

Noted
