### ISSUE TITLE
[FEATURE] Use a UI library

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/anon-chat-app#41]
### Description

@Dun-sin what are your plans on styling/ui of the app?
I think it'd be cool to use a UI library, so we can get a MVP within the shortest possible time instead of using pure tailwind css. Since using a UI library = already made components then we can change it later to match the style we want.

How do we go about this?

**Comment by Dun-sin** [comment]
I thought of that but no, I want most things to be the plain form. As I said this project is more targetted at beginners to understand basic important things like redux and socketio etc
