### ISSUE TITLE
[FEATURE] Discussion on How The System Works 

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/anon-chat-app#53]
### Description

@Dun-sin @Dharmik48 I guess now we need to have a discussion on how the system would work from pairing to chatting, etc.
What features would the system be having? would there be:
* video calls?
* group chats?

Pls let's discuss...

**Comment by Dun-sin** [comment]
I guess it's time to create my community

@renzil and @Pradumnasaraf aren't really into this project

**Comment by mathiasayivor** [comment]
> I guess it's time to create my community
> 
> @renzil and @Pradumnasaraf aren't really into this project

Oh ok

**Comment by mathiasayivor** [comment]
> I guess it's time to create my community

Absolutely!

**Comment by mathiasayivor** [comment]
So @Dun-sin what's up?

**Comment by Dun-sin** [comment]
Created the discord server @mathiasayivor

https://discord.gg/KUWjx4fygJ
