### ISSUE TITLE
[BUG] Env variables are undefined in client

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/anon-chat-app#57]
### Description

Due to migration to the recent migration to vite (#54 ), all env variables are undefined. This is because:
> To prevent accidentally leaking env variables to the client, only variables prefixed with VITE_ are exposed to your Vite-processed code

So to resolve the issue, all env variables with the prefix REACT_APP_ needs to be changed to VITE_

**Comment by Dun-sin** [comment]
@Dharmik48 complete your job. This is yours to fix

**Comment by Dharmik48** [comment]
I'll fix that after college, sorry that I missed it😅
