### ISSUE TITLE
[FEATURE] Random Pairing

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/anon-chat-app#62]
### Description

A user clicking on the start button should see searching until a room becomes available, and then the chatting interface should appear with only two users.

**Comment by mathiasayivor** [comment]
Meaning you can't chat with multiple users at the same time?

**Comment by Dun-sin** [comment]
> Meaning you can't chat with multiple users at the same time?

Yes, just 2

**Comment by mathiasayivor** [comment]
Damn! Thought you can chat with multiple users, all random.

**Comment by Dun-sin** [comment]
> Damn! Thought you can chat with multiple users, all random.

No that would be so easy to implement🙂

**Comment by mathiasayivor** [comment]
> 

Are you sure?

**Comment by mathiasayivor** [comment]
I'm not talking about a chatroom oo

**Comment by mathiasayivor** [comment]
More like how chat apps work...
Each chat is different,
e.g your chat with *user a* is different from your chat with *user b*. But you can receive message from both of them randomly and your chat session for each user is stored until the user leaves the chat.

**Comment by Dun-sin** [comment]
> More like how chat apps work... Each chat is different, e.g your chat with _user a_ is different from your chat with _user b_. But you can receive message from both of them randomly and your chat session for each user is stored until the user leaves the chat.

Nope, if you are in the search user section, you can't do that, one person at a time🙃 If you like who you are talking to, you can add them as friend(later feature), at that point it starts to act like a regular chat app

**Comment by mathiasayivor** [comment]
> > More like how chat apps work... Each chat is different, e.g your chat with _user a_ is different from your chat with _user b_. But you can receive message from both of them randomly and your chat session for each user is stored until the user leaves the chat.
> 
> Nope, if you are in the search user section, you can't do that, one person at a time🙃 If you like who you are talking to, you can add them as friend(later feature), at that point it starts to act like a regular chat app

We're on the same page then. Just that I'm already in the future 😂.

**Comment by Dun-sin** [comment]
> > > More like how chat apps work... Each chat is different, e.g your chat with _user a_ is different from your chat with _user b_. But you can receive message from both of them randomly and your chat session for each user is stored until the user leaves the chat.
> > 
> > 
> > Nope, if you are in the search user section, you can't do that, one person at a time🙃 If you like who you are talking to, you can add them as friend(later feature), at that point it starts to act like a regular chat app
> 
> We're on the same page then. Just that I'm already in the future 😂.

That's the easy part honestly, but a user can't dm someone unless they have passed through the searching stage. So when you click on add user, it's going to take both of you to a different section of the app without breaking the room connection

**Comment by jasham** [comment]
@Dun-sin I am interested in this feature can you please assign this to me.

**Comment by Dun-sin** [comment]
> @Dun-sin I am interested in this feature can you please assign this to me.

Sure

**Comment by jasham** [comment]
Thanks @Dun-sin
