### ISSUE TITLE
[DOCS] Improve the README

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/anon-chat-app#9]
### Description

- Add the screenshot of live/hosted project
- Add the tech stack logo

**Comment by dhrumishah** [comment]
Can I do this?

**Comment by kelvinparmar** [comment]
I want to contribute on this issue.
Should I contribute in this issue?

**Comment by Dun-sin** [comment]
@dhrumishah and @kelvinparmar yes you can both work on it, don't forget to add your names to `contributing.md` with your twitter handle

**Comment by kelvinparmar** [comment]
How to run this app? please give me instruction for that

**Comment by heshangambhir** [comment]
Can I Contribute to the readme

**Comment by Dun-sin** [comment]
> Can I Contribute to the readme

Go ahead

**Comment by Dharmik48** [comment]
Let me make a few improvements too

**Comment by kelvinparmar** [comment]
All the issue are not done?

**Comment by Dun-sin** [comment]
> Let me make a few improvements too

let's see what you can improve

**Comment by Dun-sin** [comment]
> All the issue are not done?

you can check the others
